<br /><br />
<div id="view-content">
	<center>
	<div style='color:black;border:1px solid red; width:300px; padding:5px;' >
		<center>
			<form action=''>
				<table>
					<tr>
						<td>Name</td>
						<td><input type='text' name='name' placeholder='Name' style='padding-left:5px;'></td>
					<tr>
					<tr>
						<td>Password</td>
						<td><input type='password' name='password' placeholder='Password' style='padding-left:5px;'></td>
					<tr>
					<tr>
						<td></td>
						<td><input type='submit' name='submit' ></td>
					<tr>
				</table>
			</form>	
		</center>
		
	<div>
	</center>
</div>